server:
  port: 8083
  
spring:
  application:
    name: api-gateway
    
eureka:
  instance:
    # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 함
    prefer-ip-address: true 
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka, http://localhost:8082/eureka
      
      